server:
  port: 8080

spring:
  application:
    name: bff

  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: ${JWT_ISSUER_URI}

  cloud:
    gateway:
      routes:
        - id: catalogo
          uri: ${CATALOGO_URL:http://localhost:8081}
          predicates:
            - Path=/api/catalog/**

        - id: shipments
          uri: ${SHIPMENTS_URL:http://localhost:5000}
          predicates:
            - Path=/api/shipments/**

      globalcors:
        add-to-simple-url-handler-mapping: true
        cors-configurations:
          '[/**]':
            allowedOrigins: ${CORS_ALLOWED_ORIGIN:http://localhost:4200}
            allowedMethods: [GET, POST, PUT, DELETE, OPTIONS]
            allowedHeaders: ["*"]
            allowCredentials: true

app:
  security:
    jwt:
      audience: ${JWT_AUDIENCE}

management:
  endpoints:
    web:
      exposure:
        include: health,info
  endpoint:
    health:
      show-details: never

info:
  app:
    name: ms-rutaexpress-bff
