server:
  port: 8080

spring:
  application:
    name: bff

  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: ${COGNITO_ISSUER_URI}

  cloud:
    gateway:
      routes:
        - id: catalogo
          uri: ${CATALOGO_URL:http://localhost:8081}
          predicates:
            - Path=/api/catalog/**

        - id: shipments
          uri: ${SHIPMENTS_URL:http://localhost:5000}
          predicates:
            - Path=/api/shipments/**

        - id: report
          uri: ${REPORT_URL:http://localhost:8082}
          predicates:
            - Path=/api/report/**

app:
  security:
    cognito:
      client-id: ${COGNITO_CLIENT_ID}
  cors:
    allowed-origin: ${CORS_ALLOWED_ORIGIN:http://localhost:4200}

management:
  endpoints:
    web:
      exposure:
        include: health,info
  endpoint:
    health:
      show-details: never

info:
  app:
    name: ms-rutaexpress-bff
